apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
configMapGenerator:
  - name: course-app-config-map
    literals:
      - APP_STORE=redis
      - APP_REDIS_URL=redis://dragonfly:6379
generatorOptions:
  disableNameSuffixHash: true